### ISSUE TITLE
Allow using local hoogle & haddock

### ISSUE THREAD

**Issue by jchia** [caneroj1/hoogle-vscode#2]
This is a feature request.

Some users have hoogle installed locally. It's faster and can be used even when Internet connection is down. It will be convenient if this extension can be configured to use the local hoogle.

**Comment by caneroj1** [comment]
I think that's a cool idea!

I've never run Hoogle locally, so I'm not too sure how it works at the moment. I'll investigate and get back to you.

Is it a server that runs locally? If so, we should just be able to change the extension's url so it hits your local instead.

**Comment by jchia** [comment]
Yes, you can run a hoogle webserver locally and visit it locally.

These are some Internet URLs paired with localhost URLs on my machine:
`http://hoogle.haskell.org/?hoogle=base`
`http://localhost:8000/?hoogle=base`

`https://hackage.haskell.org/package/base`
`http://localhost:8000/file/home/jchia/.stack/programs/x86_64-linux/ghc-8.0.2/share/doc/ghc-8.0.2/html/libraries/base-4.9.1.0/`

`https://hackage.haskell.org/package/base-4.9.1.0/docs/Control-Arrow.html`
`http://localhost:8000/file/home/jchia/.stack/programs/x86_64-linux/ghc-8.0.2/share/doc/ghc-8.0.2/html/libraries/base-4.9.1.0/Control-Arrow.html`

`https://hackage.haskell.org/package/base-4.9.1.0/docs/Control-Category.html#t:Category`
`http://localhost:8000/file/home/jchia/.stack/programs/x86_64-linux/ghc-8.0.2/share/doc/ghc-8.0.2/html/libraries/base-4.9.1.0/Control-Category.html#t:Category`

The local hoogle can also be queried from the command-line, but I suppose supporting that would be more than just changing the URL.

**Comment by caneroj1** [comment]
Hey @jchia,

I just pushed out 0.0.3 which allows you to change the URL the extension is using to query hoogle.

You can point it your local server if you'd like.

Let me know if you have any issues!

**Comment by jchia** [comment]
OK, I just tried it and it seems to work with my local hoogle. Thanks.
