### ISSUE TITLE
Startup time really high when opening a Haskell file

### ISSUE THREAD

**Issue by jbayardo** [caneroj1/hoogle-vscode#3]
- Extension Name: hoogle-vscode
- Extension Version: 0.0.4
- OS Version: Windows_NT x64 10.0.16299
- VSCode version: 1.23.0

 We have written the needed data into your clipboard. Please paste:

```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 2406,
		"activateCallTime": 2383,
		"activateResolvedTime": 0,
		"activationEvent": "onLanguage:haskell"
	}
}
```

Relevant settings are:

```json
{
    "hoogle-vscode.useCabalDependencies": true,
    "hoogle-vscode.maxResults": 10,
}
```

This happens without really issuing any searches.

**Comment by caneroj1** [comment]
I've release version 0.0.5 to address this issue.

I was able to reproduce the performance issues locally, and I think 0.0.5 addresses it. Let me know if it's still too slow for you.
