### ISSUE TITLE
Incorrect keyboard shortcut on Windows

### ISSUE THREAD

**Issue by LaurentRDC** [caneroj1/hoogle-vscode#6]
From the README, the keyboard shortcut is listed as Shift + Alt + V. However, on my Windows machine, it works only for Shift + Alt + H. 

Is this a typo in the README or is this a Windows-specific shortcut? I can't find where the shortcut is defined in the repository.

**Comment by caneroj1** [comment]
Sorry, this is a typo in the readme. The correct keybinding is Shift + Alt + H.
